#:schema ./schema.json

id = "bytebase"
name = "Bytebase"
icon = "https://avatars.githubusercontent.com/u/74386897"
description = "Bytebase is Database CI/CD for DevOps teams."
tags = ["DevOps", "CI/CD"]

[source]
image = "bytebase/bytebase:2.15.0"

[[ports]]
id = "web"
port = 8080
type = "HTTP"

[[ports]]
id = "grpc"
port = 8081
type = "HTTP"

[[volumes]]
id = "data"
dir = "/var/opt/bytebase"
