#:schema ./schema.json

id = "flowise"
name = "Flowise"
icon = "https://avatars.githubusercontent.com/u/128289781"
description = "Drag & drop UI to build your customized LLM flow."

[source]
image = "flowiseai/flowise:1.4.10"

[[ports]]
id = "web"
port = 3000
type = "HTTP"

[[volumes]]
id = "data"
dir = "/usr/src/packages"
