#:schema ./schema.json

id = "ghost"
name = "Ghost"
icon = "https://raw.githubusercontent.com/zeabur/service-icons/main/marketplace/ghost.svg"
docs = "https://zeabur.com/docs/marketplace/ghost"
description = "Ghost is a powerful app for new-media creators to publish, share, and grow a business around their content."

[source]
image = "ghost:5-alpine"

[[ports]]
id = "web"
port = 2368
type = "HTTP"

[env]
database__client = { default = "mysql" }
database__connection__host = { default = "${MYSQL_HOST}" }
database__connection__port = { default = "${MYSQL_PORT}" }
database__connection__user = { default = "${MYSQL_USERNAME}" }
database__connection__password = { default = "${MYSQL_PASSWORD}" }
database__connection__database = { default = "${MYSQL_DATABASE}" }
url = { default = "${ZEABUR_WEB_URL}" }
