#:schema ./schema.json

id = "libre-chat"
name = "Libre Chat"
icon = "https://github.com/danny-avila/LibreChat/raw/638ac5bba61a524cc4ae99711a91f19572c4f2a0/client/public/assets/logo.svg"
description = "LibreChat brings together the future of assistant AIs with the revolutionary technology of OpenAI's ChatGPT."
templateURL = "https://zeabur.com/templates/0X2ZY8"
tags = ["AI", "LLM"]

[source]
image = "ghcr.io/danny-avila/librechat:v0.6.5"

[[ports]]
id = "web"
port = 3080
type = "HTTP"

[env]
OPENAI_API_KEY = { default = "sk-xxxx", required = true }
