#:schema ./schema.json

id = "miniflux"
name = "Miniflux"
icon = "https://miniflux.app/favicon.ico"
description = "Miniflux is a minimalist and opinionated feed reader."
templateURL = "https://zeabur.com/templates/L0KM0H"
tags = ["RSS", "Feed Reader", "Miniflux"]

[source]
image = "miniflux/miniflux:2.1.2"

[[ports]]
id = "web"
port = 8080
type = "HTTP"

[env]
DATABASE_URL = { default = "${POSTGRES_CONNECTION_STRING}" }
RUN_MIGRATIONS = { default = "1" }
BASE_URL = { default = "${ZEABUR_WEB_URL}" }
ADMIN_PASSWORD = { default = "${PASSWORD}" }
ADMIN_USERNAME = { default = "Admin" }
CREATE_ADMIN = { default = "1" }
