#:schema ./schema.json

id = "minio"
name = "MinIO"
icon = "https://raw.githubusercontent.com/zeabur/service-icons/main/marketplace/minio.svg"
description = "MinIO is a high performance object storage server, designed for large-scale private cloud infrastructure."

[source]
image = "quay.io/minio/minio:latest"
command = ["/bin/bash"]
args = ["-c", "minio server /data --console-address :9090"]

[[ports]]
id = "web"
port = 9000
type = "HTTP"

[[ports]]
id = "console"
port = 9090
type = "HTTP"

[[volumes]]
id = "data"
dir = "/data"

[env]
MINIO_ROOT_USER = { default = "minio" }
MINIO_ROOT_PASSWORD = { default = "${PASSWORD}" }

MINIO_CONSOLE_URL = { default = "${ZEABUR_CONSOLE_URL}", expose = true, readonly = true }
MINIO_USERNAME = { default = "${MINIO_ROOT_USER}", expose = true, readonly = true }
MINIO_PASSWORD = { default = "${MINIO_ROOT_PASSWORD}", expose = true, readonly = true }

[[instructions]]
title = "Go to MinIO Console"
type = "URL"
content = "${MINIO_CONSOLE_URL}"

[[instructions]]
title = "MinIO Username"
type = "TEXT"
content = "${MINIO_USERNAME}"

[[instructions]]
title = "MinIO Password"
type = "PASSWORD"
content = "${MINIO_PASSWORD}"
