#:schema ./schema.json

id = "n8n"
name = "n8n"
description = "Build complex automations 10x faster, without fighting APIs"
icon = "https://i.imgur.com/AaKxvK2.png"
docs = "https://zeabur.com/docs/marketplace/n8n"
templateURL = "https://zeabur.com/templates/W2H4RW"
tags = ["Automation", "Workflow"]

[source]
image = "n8nio/n8n:1.21.1"

[[ports]]
id = "web"
port = 5678
type = "HTTP"

[[volumes]]
id = "data"
dir = "/home/node/.n8n"

[env]
DB_TYPE = { default = "postgresdb" }
DB_POSTGRESDB_USER = { default = "${POSTGRES_USERNAME}" }
DB_POSTGRESDB_PASSWORD = { default = "${POSTGRES_PASSWORD}" }
DB_POSTGRESDB_HOST = { default = "${POSTGRES_HOST}" }
DB_POSTGRESDB_PORT = { default = "${POSTGRES_PORT}" }
DB_POSTGRESDB_DATABASE = { default = "${POSTGRES_DATABASE}" }
WEBHOOK_URL = { default = "${ZEABUR_WEB_URL}" }

[[init]]
id = "init-chown-data"
command = ["chown", "-R", "1000:1000", "/home/node/.n8n"]
image = "busybox"

[[init.volumes]]
id = "data"
mountPath = "/home/node/.n8n"
