#:schema ./schema.json

id = "teable"
name = "Teable"
icon = "https://avatars.githubusercontent.com/u/113977713"
description = "A Super fast, Real-time, Professional, Developer friendly, No code database."
templateURL = "https://zeabur.com/templates/QF8695"
tags = ["Database", "No Code"]

[source]
image = "ghcr.io/teableio/teable:latest"

[[volumes]]
id = "data"
dir = "/app/.assets"

[[ports]]
id = "web"
port = 3000
type = "HTTP"

[env]
TZ = { default = "Asia/Shanghai" }
NODE_OPTIONS = { default = "--max-old-space-size=1024" }
PUBLIC_ORIGIN = { default = "${ZEABUR_WEB_URL}" }
PRISMA_DATABASE_URL = { default = "${POSTGRES_CONNECTION_STRING}" }
