#:schema ./schema.json

id = "vaultwarden"
name = "vaultwarden"
icon = "https://github.com/dani-garcia/vaultwarden/raw/main/resources/vaultwarden-icon.svg"
description = "A Bitwarden compatible server written in Rust."
tags = ["Password Management"]

[source]
image = "vaultwarden/server:1.29.2"

[[ports]]
id = "web"
port = 80
type = "HTTP"

[[volumes]]
id = "data"
dir = "/data"
